### ISSUE TITLE
Create DB setup script

### ISSUE THREAD

**Issue by JakubOciepa** [JakubOciepa/Contador#19]
Create script which will create and setup MySQL database for the Rest API. After running this script the database should be ready to use by the Rest API so all columns, procedures etc. should be created. 

Database should have created:
- [x] Tables
- [x] Stored procedures

*Example of usage:*
`$ > setupDatabase.sh/ps1 dbPath? user password`

You can use scripts from the `Contador.Web.Db>dbo`.

After creating this script please place it in the *Scripts* directory in the main folder.

**Comment by ShanSanear** [comment]
Created script has been tested under WSL using Powershell Core. Should also work on Windows, using Powershell / Powershell Core.
